name: Build C Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libssl-dev

      - name: Compile encrypt.c
        run: gcc src/encrypt.c -o encrypt -lcrypto

      - name: Compile decrypt.c
        run: gcc src/decrypt.c -o decrypt -lcrypto
